#!/bin/sh

# Display & monitor setup
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 100 --rotate normal --brightness 1.0 &

# Wallpaper
xwallpaper --zoom ~/Pictures/Wallpapers/lonely-house.jpg

# Repeat rate
xset r rate 300 50 &

# Disable Caps Lock
setxkbmap -option caps:none &

# Normal cursor instead of X one
xsetroot -cursor_name left_ptr &

# Xresources
xrdb -merge ~/.config/X11/Xresources &

# Remove anoying beep sounds
xset b off &

# Auto-locker
xautolock -time 10 -locker slock &

# Dbus
export $(dbus-launch)

# Pipewire
pipewire &
pipewire-pulse &
wireplumber &

